pushd
cd Kxsarl
python qHead.py > Source/AllHeaders.hpp
echo "" "" "// Please note that this is just a quick file generated by a Python script" "// It was only because I was getting lazy and dead tired of all those #include lines all the time" "// I know this is lazy and dirty and I DO NOT CARE so you don't have to tell me! Okay?" >> Source/AllHeaders.hpp
popd
echo Done