// Lic:
// the Legend of the Kxsarl
// Just all headers combined together by a quick Python Script out of laziness. Dirty, huh?
// 
// 
// 
// (c) Jeroen P. Broks, 2023
// 
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
// 
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
// You should have received a copy of the GNU General Public License
// along with this program.  If not, see <http://www.gnu.org/licenses/>.
// 
// Please note that some references to data like pictures or audio, do not automatically
// fall under this licenses. Mostly this is noted in the respective files.
// 
// Version: 23.08.06
// EndLic
#include "../Headers/Debug.hpp"
#include "../Headers/Version.hpp"
#include "../Headers/Error.hpp"
#include "../Headers/MainMenu.hpp"
#include "../Headers/Textboxes.hpp"
#include "../Headers/Music.hpp"
#include "../Headers/Config.hpp"
#include "../Headers/CharacterCreation.hpp"
#include "../Headers/Stats.hpp"
#include "../Headers/RollStat.hpp"
#include "../Headers/ArmorClass.hpp"
#include "../Headers/SysStatus.hpp"
#include "../Headers/PickCharacter.hpp"
#include "../Headers/GlobGFX.hpp"
#include "../Headers/PickGameSlot.hpp"
#include "../Headers/UseJCR6.hpp"
#include "../Headers/Game_Narration.hpp"
#include "../Headers/Game_AutoMap.hpp"
#include "../Headers/Game_New.hpp"
#include "../Headers/Game_Config.hpp"
#include "../Headers/Game_Map.hpp"
#include "../Headers/Game_Inventory.hpp"
#include "../Headers/Game_Crawl.hpp"
#include "../Headers/Game_MiniConsole.hpp"
#include "../Headers/Flow.hpp"
#include "../Headers/Game_Debug.hpp"
#include "../Headers/Jukebox.hpp"


// Please note that this is just a quick file generated by a Python script
// It was only because I was getting lazy and dead tired of all those #include lines all the time
// I know this is lazy and dirty and I DO NOT CARE so you don't have to tell me! Okay?